name: Sync Specific Release Files

on:
  schedule:
    - cron: '0 0 * * *'  # 每天自动同步
  workflow_dispatch:  # 允许手动触发

jobs:
  check_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Check if IVESTEST secret exists
        run: |
          if [ -z "${{ secrets.IVESTEST }}" ]; then
            echo "IVESTEST secret is not set"
            exit 1
          else
            echo "IVESTEST secret is set"
          fi

      - name: Fetch latest release from private repo
        id: get_latest_release
        run: |
          LATEST_RELEASE=$(curl -s -H "Authorization: token ${{ secrets.IVESTEST }}" \
            https://api.github.com/repos/iveslee308/Rafael-SDK-Internal/releases/latest | jq -r '.tag_name')
          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV
          
