name: Sync Specific Release Files

on:
  schedule:
    - cron: '0 0 * * *'  # 每天自动同步
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: "check is IVESTEST exists"
        env: 
            super_secret: ${{ secrets.IVESTEST }}
        if: ${{ env.super_secret == 'IVESTEST' }}
        run: 
          echo "the secret \"IVESTEST\" has not been made;
