name: Sync Specific Release Files

on:
  schedule:
    - cron: '0 0 * * *'  # 每天自动同步
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repository
        uses: actions/checkout@v4

      - name: Set the release version
        run: |
          export LATEST_RELEASE=$(gh release list --repo iveslee308/Rafael-SDK-Internal --limit 1 --json tagName -q ".[0].tagName")
          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV

      - name: Fetch latest release from private repo
        id: get_latest_release
        run: |
          LATEST_RELEASE=$(curl -s -H "Authorization: token ${{ secrets.IVESTEST }}" \
            https://api.github.com/repos/iveslee308/Rafael-IoT-SDK-Internal/releases/latest | jq -r '.tag_name')
          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV
          
      - name: Print latest release version
        run: echo $LATEST_RELEASE 
