name: Sync Specific Release Files

on:
  schedule:
    - cron: '0 0 * * *'  # 每天自动同步
  workflow_dispatch:  # 允许手动触发

jobs:
  check_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check if IVESTEST secret exists
        run: |
          if [ -z "${{ secrets.IVESTEST }}" ]; then
            echo "IVESTEST secret is not set"
            exit 1
          else
            echo "IVESTEST secret is set"
          fi

      - name: Checkout public repository
        uses: actions/checkout@v2

      - name: Fetch latest release from private repo
        id: get_latest_release
        run: |
          RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.IVESTEST }}" \
            https://api.github.com/repos/iveslee308/Rafael-IoT-SDK-Internal/releases/latest)
          
          echo "API Response: $RESPONSE"
          
          if [[ "$RESPONSE" == *"Not Found"* ]]; then
            echo "Error: No release found."
            exit 1
          fi

          LATEST_RELEASE=$(echo "$RESPONSE" | jq -r '.tag_name')
          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV
          
