name: Sync Specific Release Files

on:
  schedule:
    - cron: '0 0 * * *'  # 每天自动同步
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repository
        uses: actions/checkout@v4
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          
      - name: Fetch latest release from private repo
        id: get_latest_release
        run: |
          LATEST_RELEASE=$(curl -s -H "Authorization: token ${{ secrets.GH_PAT }}" \
            https://github.com/iveslee308/Rafael-SDK-Internal/releases/latest | jq -r '.tag_name')
          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV

      - name: Download selected files from private release
        run: |
          mkdir release-assets
          gh release download $LATEST_RELEASE --repo iveslee308/Rafael-SDK-Internal \
            --dir release-assets --pattern "Dosc\*"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Create release in public repo
        run: |
          gh release create $LATEST_RELEASE release-assets/* --repo iveslee308/Rafael-SDK-Internal \
            --title "Release $LATEST_RELEASE" --notes "Auto-synced from internal repo"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
