name: Sync Specific Release Files

on:
  schedule:
    - cron: '0 0 * * *'  # 每天自动同步
  workflow_dispatch:  # 允许手动触发

jobs:
  check_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Check if IVESTEST secret exists
        run: |
          if [ -z "${{ secrets.IVESTEST }}" ]; then
            echo "IVESTEST secret is not set"
            exit 1
          else
            echo "IVESTEST secret is set"
          fi

      - name: Fetch latest release from private repo
        id: get_latest_release
        run: |
          LATEST_RELEASE=$(curl -s -H "Authorization: token ${{ secrets.IVESTEST }}" \
            https://api.github.com/repos/iveslee308/Rafael-SDK-Internal/releases/ | jq -r '.tag_name')
          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV
          
      - name: Download selected files from private release
        run: |
          mkdir release-assets
          gh release download $LATEST_RELEASE --repo iveslee308/Rafael-SDK-Internal \
            --dir release-assets --pattern "RT58x_SDK_Release_Notes.pdf"
        env:
          GH_TOKEN: ${{ secrets.IVESTEST }}

      - name: Create release in public repo
        run: |
          gh release create $LATEST_RELEASE release-assets/* --repo iveslee308/Rafael-SDK \
            --title "Release $LATEST_RELEASE" --notes "Auto-synced from internal repo"
        env:
          GH_TOKEN: ${{ secrets.IVESTEST }} 
