name: Sync Specific Release Files

on:
  schedule:
    - cron: '0 0 * * *'  # 每天自动同步
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repository
        uses: actions/checkout@v4

      - name: Fetch latest release from private repo
        id: get_latest_release
        run: |
          LATEST_RELEASE=$(curl -s -H "Authorization: token ${{ secrets.GH_PAT }}" \
            https://api.github.com/repos/iveslee308/Rafael-SDK-Internal/releases/latest | jq -r '.tag_name')
          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV

      - name: Read sync_files.txt
        id: read_files
        run: |
          echo "Downloading files listed in sync_files.txt..."
          cat sync_files.txt | while read file; do
            if [ -n "$file" ]; then
              echo "Downloading: $file"
              gh release download $LATEST_RELEASE --repo iveslee308/Rafael-SDK-Internal \
                --dir release-assets --pattern "$file"
            fi
          done
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

      - name: Checkout public repo (main branch)
        uses: actions/checkout@v4
        with:
          ref: main  # 确保操作的是 main 分支
      
      - name: Read sync_files.txt & Copy Files
        run: |
          cat sync_files.txt | while read file; do
            if [ -n "$file" ]; then
              echo "Downloading: $file"
              gh release download $LATEST_RELEASE --repo iveslee308/Rafael-SDK-Internal \
                --dir . --pattern "$file"
            fi
          done
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
      
      - name: Commit and Push Changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Synced files from internal repo (Release $LATEST_RELEASE)" || echo "No changes to commit"
          git push origin main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
